services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    Harryn\Jacobn\AutomationBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Package,Templates,Migrations,Tests}'
    
    Harryn\Jacobn\AutomationBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
    
    Harryn\Jacobn\AutomationBundle\Fixtures\:
        resource: '../../Fixtures/*'
        tags: ['doctrine.fixture.orm']
    
    Harryn\Jacobn\AutomationBundle\EventListener\WorkflowListener:
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: jacobn.automation.workflow.execute, method: executeWorkflow }
    
    Harryn\Jacobn\AutomationBundle\EventListener\PreparedResponseListener:
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: jacobn.automation.prepared_response.execute, method: executePreparedResponse }
    
    # Public aliases
    jacobn.automations:
        public: true
        class: Harryn\Jacobn\AutomationBundle\Services\AutomationService
    
    jacobn.automations.workflows:
        alias: Harryn\Jacobn\AutomationBundle\EventListener\WorkflowListener
        public: true
    
    jacobn.automations.prepared_responses:
        alias: Harryn\Jacobn\AutomationBundle\EventListener\PreparedResponseListener
        public: true
